# Generated by Django 5.2.6 on 2025-09-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vaultitem_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultitem',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='competition_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='market_potential',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='revenue_model',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('research', 'Research Phase'), ('planning', 'Planning'), ('development', 'In Development'), ('testing', 'Testing'), ('launched', 'Launched'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='target_audience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
