# Generated by Django 5.2.6 on 2025-10-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vaultitem_category_vaultitem_competition_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultitem',
            name='category',
            field=models.CharField(blank=True, choices=[('Tech', 'Tech'), ('Health', 'Health'), ('Finance', 'Finance'), ('Education', 'Education'), ('E-commerce', 'E-commerce'), ('Social', 'Social'), ('Gaming', 'Gaming'), ('Other', 'Other')], max_length=100),
        ),
    ]
